### ISSUE TITLE
[Frontend] Source field in NodeSearchComponent should filter both literal and class nodes.

### ISSUE THREAD

**Issue by punith300i** [usc-isi-i2/sand#23] opened 2023-07-01 01:43 UTC
The current implementation of the source filed in NodeSearch component filters only the class nodes, it needs to be updated to filter both literal and class nodes.

**Comment by binh-vu** [comment] 2023-07-02 04:29
Duplicate of #18

**Closed by binh-vu** 2023-07-02 04:29 UTC
